# Сервер
server:
  port: 8081

# Spring
spring:
  application:
    name: "Book Expert Backend"
  r2dbc:
    jpa:
      open-in-view: false
      show-sql: false
      generate-ddl: false
      hibernate:
        ddl-auto: validate
    liquibase:
      drop-first: false
      change-log: classpath:db/changelog/db.changelog-master.xml
      enabled: true
      url: jdbc:postgresql://localhost:5432/postgres
      user: postgres
      password: 0
      default-schema: book_expert

grpc:
  port: 6565

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: true
    role: ADMIN
  context-path: /actuator

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG
    ru:
      seranov:
        bookexpert: DEBUG

# Приложение
app:
  version: '@project.version@'
  database:
    postgresBookExpert:
      pool:
        enabled: true
        initial-size: 5
        max-size: 10
        validation-query: SELECT
      url: r2dbc:postgresql://localhost:5432/postgres
      schema: book_expert
      username: postgres
      password: 0
    mongoBooks:
      pool:
        enabled: true
        initial-size: 6
        max-size: 11
        validation-query: SELECT
      url: mongodb://localhost:27017/postgres
      schema: books
